### ISSUE TITLE
can't log in,can not send assets (nft, token)

### ISSUE THREAD

**Issue by shirinyoko** [BitskiCo/bitski-js#473]
I don't know about GitHub but I want to ask if Bitski is still running? I've been having issues lately

- Can't log in, Bitski keeps asking me to enter my email, even though I've done it several times

- Can't send, an error always appears when I want to send something from Bitski

**Comment by chronicIntrovert** [comment]
@shirinyoko - Bitski should still be running. Can you provide more details? 

1. Are you using wallet.bitski.com, our extension, or iOS app?
2. Can you attach any screenshots or videos of errors you're seeing?
3. What is your username or wallet address being affected?

**Comment by shirinyoko** [comment]
1.I use bitski extension
2.I sent 2 videos
  A. It's difficult to send tokens or NFT, it always happens like this
     video :https://www.mediafire.com/file/amcx2lgrm82vah8/Untitled+video+-+Made+with+Clipchamp+(1).mp4/file

  B. This is an example of my difficulty when I want to log in, there are 2 versions in the video and the version where a pop up appears from Bitski but after that it just loads like in the video 
video : https://www.mediafire.com/file/548tt1ytq12thb4/Record_2024_02_20_00_30_36_103.mp4/file

3.0x6c27eb999e2260728f0331bc507a1f14722bee81

I'm not the only one experiencing this problem, but people in the sandbox who use Bitski for wallets also experience the same thing.
actually it started to feel like it was at the end of December, but it started to get worse recently.
I sent the video via mediafire

**Comment by chronicIntrovert** [comment]
@shirinyoko - please attach the video directly as a comment. For security reasons, we cannot open the Mediafire files.

**Comment by shirinyoko** [comment]
https://github.com/BitskiCo/bitski-js/assets/93244983/4d75f1fd-469b-4560-8bfa-2c6d8c7260f8


https://github.com/BitskiCo/bitski-js/assets/93244983/acdc90b4-727c-405b-8940-12e67da16e24


https://github.com/BitskiCo/bitski-js/assets/93244983/1056ffbf-36c9-4e55-afe8-ac7968e5a1a8


https://github.com/BitskiCo/bitski-js/assets/93244983/3c09fa3f-9a5b-4a36-be4a-e5de5c9fe9e1

**Comment by shirinyoko** [comment]
The reason I sent MediaFire was because the first video was too big, so I made it into 3 parts here

so parts 1-3 of the video about my complaint are difficult to send tokens/nft

The last video had difficulty logging in

**Comment by chronicIntrovert** [comment]
@shirinyoko - can you try clearing you browser's cookies and storage? That should resolve your issues.

**Comment by shirinyoko** [comment]
> @shirinyoko - can you try clearing you browser's cookies and storage? That should resolve your issues.

I have done this, including trying on another browser and trying on Android (Kiwi/Mises) but the problem remains the same if I want to send it will happen.

one of my friends tried to contact the sandbox, and the answer was like this.

I hope you can overcome this because we are quite frustrated. Moreover Bitski didn't give us 12 words to try in another extension (metamasak)
![Screenshot (553)](https://github.com/BitskiCo/bitski-js/assets/93244983/e8e36d0c-f7d1-404f-bb55-7fdf00813584)

**Comment by chronicIntrovert** [comment]
> > @shirinyoko - can you try clearing you browser's cookies and storage? That should resolve your issues.
> 
> I have done this, including trying on another browser and trying on Android (Kiwi/Mises) but the problem remains the same if I want to send it will happen.
> 
> one of my friends tried to contact the sandbox, and the answer was like this.
> 
> I hope you can overcome this because we are quite frustrated. Moreover Bitski didn't give us 12 words to try in another extension (metamasak) ![Screenshot (553)](https://private-user-images.githubusercontent.com/93244983/306815688-e8e36d0c-f7d1-404f-bb55-7fdf00813584.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MjQ1ODUsIm5iZiI6MTcwODYyNDI4NSwicGF0aCI6Ii85MzI0NDk4My8zMDY4MTU2ODgtZThlMzZkMGMtZjdkMS00MDRmLWJiNTUtN2ZkZjAwODEzNTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE3NTEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZDBhODRhNzUzMzY2MzcxYjA5NmIwYzgzYzJiYTExZmNhZjk2ZmU2YzJmMjdiNDFmOTIzMjhhY2RjZmIwOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NFkF844f4pPSPjKUNZLNxgd6wBV25f1W5Si4FPQ_By4)

Ok, thanks for the update @shirinyoko - we'll investigate further. Until then, you can feel free to use wallet.bitski.com to attempt to send transactions. Let us know if you have any issues.

**Comment by pzuraq** [comment]
@shirinyoko quick question here, are you going between different user accounts, e.g. logging in and out of one account and switching to another? 

What's happening when you get to the signer flow from extension appears to be that you are logged in as a different user than the one that is attempting to sign. We recently implemented some changes to add better support for multi-account switching, but it appears there's a situation where the extension can get confused and not tell the signer which user is attempting to sign, thus the error messages.

We'll get to work on the fix for that! In the meantime, if you logout of everything and then log back in as one user, you should be able to sign from the extension. But if you never switched accounts on this machine, definitely let us know because that means something else is going on.

**Comment by pzuraq** [comment]
@shirinyoko we have shipped the fix for our signer, so in general you should be able to log into multiple accounts, switch accounts, etc. and not run into this issue anymore in the extension. Let us know if you're still having issues!

Re: Logging into the sandbox, can you try disabling the extension and logging in via the webflow? Wanting to see if there's something specific to the extension that's causing it to hang.

**Comment by shirinyoko** [comment]
> @shirinyoko quick question here, are you going between different user accounts, e.g. logging in and out of one account and switching to another?
> 
> What's happening when you get to the signer flow from extension appears to be that you are logged in as a different user than the one that is attempting to sign. We recently implemented some changes to add better support for multi-account switching, but it appears there's a situation where the extension can get confused and not tell the signer which user is attempting to sign, thus the error messages.
> 
> We'll get to work on the fix for that! In the meantime, if you logout of everything and then log back in as one user, you should be able to sign from the extension. But if you never switched accounts on this machine, definitely let us know because that means something else is going on.

I use 3 Bitski accounts, but 2 of them are in different browsers. I did that so I didn't have to bother logging in/logging out.

**Comment by pzuraq** [comment]
> Currently I am focusing on how to send tokens to the Bitski web extension but the error still occurs
>
> however yesterday I found a temporary solution using web catalog.bitski which worked well

Ok, that's good to hear! We'll continue to work on the issue and try to see if we figure out what is going wrong in cases where multiple accounts are signed in on a single machine. Multi-account usage has been a pain point for a while, and we want to make it as smooth as possible to switch between them.

> The token was successfully sent even though an error appeared during sending (I forgot to screenshot)

It's good that it was sent, that's the most important part, but if you do see the error again it would definitely be helpful to get some more details so we can figure out what's going on.

> for the log in/log out problem, I tried asking several people in the sandbox whether the problem had been resolved or not

This can be an issue for a few reasons, some of which would be improper integration on the dApp side, but some of which would be from bugs in the extension injection code. That's why I was wondering if it works for you when disabling the extension, that'll help us narrow it down.

You can also email us directly at support@bitski.com if you would like to provide more details or do more troubleshooting!

**Comment by shirinyoko** [comment]
> > Currently I am focusing on how to send tokens to the Bitski web extension but the error still occurs
> > however yesterday I found a temporary solution using web catalog.bitski which worked well
> 
> Ok, that's good to hear! We'll continue to work on the issue and try to see if we figure out what is going wrong in cases where multiple accounts are signed in on a single machine. Multi-account usage has been a pain point for a while, and we want to make it as smooth as possible to switch between them.
> 
> > The token was successfully sent even though an error appeared during sending (I forgot to screenshot)
> 
> It's good that it was sent, that's the most important part, but if you do see the error again it would definitely be helpful to get some more details so we can figure out what's going on.
> 
> > for the log in/log out problem, I tried asking several people in the sandbox whether the problem had been resolved or not
> 
> This can be an issue for a few reasons, some of which would be improper integration on the dApp side, but some of which would be from bugs in the extension injection code. That's why I was wondering if it works for you when disabling the extension, that'll help us narrow it down.
> 
> You can also email us directly at [support@bitski.com](mailto:support@bitski.com) if you would like to provide more details or do more troubleshooting!

OK, maybe that's enough for now as long as there are alternatives that I can use while waiting for the Bitski team to fix it.

I've sent emails, chatted with official accounts on Twitter and Discord but no one responded, only here you guys responded well. So I'll come back if I experience a similar problem later.

For this issue, you can close or open it if you want to provide an update

Thank you very much

**Comment by pzuraq** [comment]
Sounds good! It seems like our email forwarding was not setup properly, but it should be back online now and future messages to support@bitski.com should reach the dev team. Sorry about that!
